### ISSUE TITLE
Connection Complete event reports incorrect status

### ISSUE THREAD

**Issue by ArticuNode** [DigiExam/simplewifi#18]
Hi, thanks for this, it really works well :)

Just have noticed though, on Windows XP (I know, upgrade right? :P ) when the connection is successful, the OnConnectedComplete event still returns false.  I haven't looked into it too much though, currently working around it by listing the connections and ensuring the selected one is connected which works fine.  Just thought I'd bring this up.

Again, nice work with this :+1:

**Comment by aismelva** [comment]
Hi,

This bug was fixed ?

Still in Windows Xp Sp3

Best regards,
    Jakclyn

**Comment by ArticuNode** [comment]
There hasn't been a commit since I raised the bug so guessing not..  I can confirm later today

**Comment by aismelva** [comment]
Hi,

You can see something about the issue?

Best regards,
     Aismel

2018-02-05 9:41 GMT-05:00, RedSpiderMkV <notifications@github.com>:

**Comment by ArticuNode** [comment]
Took a while to bring my ancient laptop up to scratch but yes, the problem persists.
Seeing as Windows XP is very dead now, probably can close as unsupported.  Will leave it to the author to decide

**Comment by aismelva** [comment]
Ok,

It's sad because work's super fine and don't think the issue is a big problem.

Best regards,
Aismel

2018-02-07 8:38 GMT-05:00, RedSpiderMkV <notifications@github.com>:
